Repository gardener/pvc-autoscaler, pull requests merged in 2024-10, with the labels that each got.

#10 ci: bump Go version to 1.23.2
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#15 Enable Static Application Security Testing (SAST)
  .golangci.yml
Labels: needs/ok-to-test, needs/review, size/xs

#13 Bugfix: Skip expansion if Prometheus metrics are out-of date.
  config/default/manager_config_patch.yaml
  dist/install.yaml
  go.mod
  internal/common/common.go
  internal/periodic/periodic.go
  internal/periodic/periodic_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, size/s
